# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: claude-loop

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - main: ./cmd/claude-loop
    binary: claude-loop
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/DeukWoongWoo/claude-loop/internal/version.Version={{.Version}}
      - -X github.com/DeukWoongWoo/claude-loop/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/DeukWoongWoo/claude-loop/internal/version.BuildDate={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^Merge "
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999

release:
  github:
    owner: DeukWoongWoo
    name: claude-loop
  prerelease: auto
  name_template: "{{ .Tag }}"
  header: |
    ## claude-loop {{ .Tag }}

    Autonomous AI development loop CLI with 4-Layer Principles Framework.
  footer: |
    **Full Changelog**: https://github.com/DeukWoongWoo/claude-loop/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Installation

    **Homebrew:**
    ```bash
    brew tap DeukWoongWoo/tap
    brew install --cask claude-loop
    ```

    **Script:**
    ```bash
    curl -fsSL https://raw.githubusercontent.com/DeukWoongWoo/claude-loop/main/install.sh | bash
    ```

homebrew_casks:
  - name: claude-loop
    repository:
      owner: DeukWoongWoo
      name: homebrew-tap
    directory: Casks
    homepage: https://github.com/DeukWoongWoo/claude-loop
    description: Autonomous AI development loop CLI with 4-Layer Principles Framework
    binaries:
      - claude-loop
